### ISSUE TITLE
Update darktable.org contact page

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtorg#118]
Contact page currently has

> **development mailing list:** bugs, ideas, patches, translations – all goes here. This is also the right place to report vulnerabilities.

This should be updated to reflect that **github** is the place for these things, though I'm not sure what we should say the mailing list is for.

**Comment by johnny-bit** [comment]
I was just about to post this as an issue here :)

Mailing list can be still used as a place to post all those things, but with intent only for those who are scared shirtless of "ms github stealing data" or some other thing.

My rough idea for "contact" stuff would be:

1. Move mailing lists to some "bottom" section
2. mention that github is primary development focus, that means issues, development, translation etc takes place on github
3. mention pixls.us as hub for users
4. leave IRC as is (since it's for nerds anyway)
5. on mailing list section do mention that since primary dev place is github, there should be no expectations that devs even bother reading mailing list and that reports might go to `/dev/null`

;)

**Comment by elstoc** [comment]
Sounds good to me

**Comment by patdavid** [comment]
Where is the translation stuff on the repo?  I'm writing new copy for this page per your recommendations.

**Comment by elstoc** [comment]
Not sure how all that works - here's a link to a recent translation commit if that helps: https://github.com/darktable-org/darktable/commit/98297ccfca4a7c97f5649d470842379838a6469a

**Comment by criadoperez** [comment]
Also in the contact page it displays Facebook, Twitter and Flickr. Its missing the Mastodon link.  I included it in [PR 134](https://github.com/darktable-org/dtorg/pull/134)
