### ISSUE TITLE
Way too much static files and hard to maintain

### ISSUE THREAD

**Issue by yamalameyooooo** [darktable-org/dtorg#244]
Hello, 

I was going through the UI and the code and i have observed that:
1. UI elements, fonts are not in sync with the product
2. There are too many files to maintain and its hardcoded.
3. UX feels a bit old, way too much information in the website which users can skip.
4. Not having a changelog pop up upon application load for the first time mentioning whats new in version X.X.1

My suggestions:
Lets have a revamp, have a UI framework (react) which will be easy to maintain and will be picked up by community easily.
We can have an estimate of 4 weeks where we can redesign the webpage with more unified layout which can be maintained easily.
and having an UI framework and library will give us more UI features for example the list of supported camera is a long list of camera. It is being fetched from the MD file. But imagine opening this in a mobile and user has to scroll for way too much just to find his camera name.
Instead we can have a datatable, with search functionality

Similarly we can have many things in the revamp.

Let me know if this is a good idea, i am having some amount of time to contribute in it.
More over we can use Patternfly framework for the UI.

let me know if this helps

**Comment by elstoc** [comment]
Hmm. I think I pretty much agree with all of your numbered observations (except maybe point 2), and I think they could all be managed with relatively small and incremental changes within the existing framework - I don't think any of them need a complete rewrite.

> Lets have a revamp, have a UI framework (react) which will be easy to maintain and will be picked up by community easily

You're assuming there is a "community" maintaining this website and that they're all technically able to maintain React code. I think both assumptions are incorrect. Also, React isn't really a **UI** framework and generally assumes that there's a backend (API) to interact with. This site is statically generated (there's not really any "state" to manage in a static site) and AFAIK we intend to keep it that way, but there's nothing wrong with revamping the UI.

> We can have an estimate of 4 weeks where we can redesign the webpage with more unified layout which can be maintained easily.

I think you're overestimating the amount of time the maintainers have or would like to devote to such a project. We did quite a big rework of the site recently to move it from one static site generator to another and that took waaay more than 4 weeks. There are currently three very part-time maintainers and we don't really have the time (or desire) to devote to another complete rewrite. The reason the site mostly consists of markdown files is precisely to make them easy to contribute for non-technical users, yet we still have virtually no contributions to this repository.

> But imagine opening this in a mobile and user has to scroll for way too much just to find his camera name. Instead we can have a datatable, with search functionality.

You can't search within a web page? Not sure what benefit we get from this, though again, happy to discuss, perhaps under a separate ticket.

Love your enthusiasm, though, and we're certainly happy to take proposals, but my advice would be to break your ideas down into smaller chunks of useful work rather than take on a massive programme of change that the maintainers will probably not have the capacity to support.

**Comment by paperdigits** [comment]
While I am totally open to a redesign of the site with some nice modern features, moving away from hugo is not in the cards.
